### ISSUE TITLE
[버그] 실시간 관련 함수들 동작 불가

### ISSUE THREAD

**Issue by wollala** [Soju06/python-kis#25]
### 버그 설명
실시간 관련 함수가 동작을 안합니다.
아래와 같은 에러가 발생
```
Traceback (most recent call last):
  File "C:\Users\junpa\Workspace\PycharmProjects\wSplit\test\logs\live.py", line 37, in <module>
    app.run()
  File "C:\Users\junpa\Workspace\PycharmProjects\wSplit\test\logs\live.py", line 23, in run
    stock.rt_add("체결가", timeout=100)
  File "C:\Users\junpa\Workspace\PycharmProjects\wSplit\venv\Lib\site-packages\pykis\scope\stock\stock.py", line 72, in rt_add
    return self.rtclient.add(id, self.code, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junpa\Workspace\PycharmProjects\wSplit\venv\Lib\site-packages\pykis\rtclient\rtclient.py", line 352, in add
    return self.register(_rtcd(id, self.key.virtual_account), tr_key, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junpa\Workspace\PycharmProjects\wSplit\venv\Lib\site-packages\pykis\rtclient\rtclient.py", line 327, in register
    return self._send_request(tr_id, tr_key, True, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junpa\Workspace\PycharmProjects\wSplit\venv\Lib\site-packages\pykis\rtclient\rtclient.py", line 324, in _send_request
    return self._wait_response(id, timeout)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junpa\Workspace\PycharmProjects\wSplit\venv\Lib\site-packages\pykis\rtclient\rtclient.py", line 291, in _wait_response
    (future,) = as_completed([future], timeout=timeout)
    ^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 239, in as_completed
    raise TimeoutError(
TimeoutError: 1 (of 1) futures unfinished
```

### 재현 코드

```
from pykis import *
from utils.settings import Settings


class TradeLive(object):
    def __init__(self):
        self.kis = PyKis(
            appkey=Settings().MOCK_KIS['appkey'],
            appsecret=Settings().MOCK_KIS['appsecret'],
            virtual_account=True,
        )

    def __enter__(self):
        return self

    def __exit__(self, type_unused, value_unused, traceback_unused):
        pass

    def run(self):
        self.kis.rtclient.event.cntg.add(self.on_cntg)
        self.kis.rtclient.event.oder.add(self.on_oder)
        stock = self.kis.stock("000660")
        stock.rt_add("체결가", timeout=100)

    def on_cntg(self, cli: KisRTClient, res: KisRTPrice):
        print(f'시간: {res.stck_cntg_hour.strftime("%H:%M:%S")}', end=" ")

    def on_oder(self, cli: KisRTClient, res: KisRTConclude):
        print(
            f"{res.acnt_no} {res.acpt_yn_name} {res.cntg_isnm} {res.cntg_yn_name} {res.order_kind_name}",
            end=" ",
        )

app = TradeLive()
app.run()
input()
```

### 개발 환경
파이썬 3.11
우분투 22.04

**Comment by wollala** [comment]
자체 해결하였고 기록을 위해 남깁니다.
websocket-client 모듈 버전이 낮아서 발생한 문제였으며 버전업하여 해결하였습니다.
