### ISSUE TITLE
[질문] 자동 종목 파싱 기능 제거 방법

### ISSUE THREAD

**Issue by jhyunetp** [Soju06/python-kis#7]
### 질문 내용
[문장을 지우고, 질문 내용을 작성합니다.]
자동 종목 파싱 기능 Deactivate 방법 질의드립니다.
만약 어렵다면 해당 파싱된 정보들이 어디서 사용되는지 알 수 있을까요?

**Comment by Soju06** [comment]
먼저 자동 종목 파싱은 `market_auto_sync`가 활성화 되어있을 때 `PyKis`객체 생성 후 한 번, 24시간에 한 번씩 `sync_all`합니다.

`PyKis`를 객체를 생성할 때 `market_auto_sync`인자를 `False`를 주어 종목 자동 동기화를 끌 수 있습니다.
하지만 이는 권장하는 방법이 아니며, 종목 정보 조회의 거의 모든 부분이 `KisMarketClient`에 의존하기 때문에 자동 동기화를 사용하지 않으려면 무조건 PyKis 조회 사용 전 `kis.market.sync_all()` 함수를 호출해야합니다.

호출하지 않으면 종목 DB가 비어있거나 오래되어 조회가 불가능합니다.

아래는 `market_auto_sync`를 `False`로 한 예제입니다.
```py
kis = PyKis(
    appkey=APPKEY,
    appsecret=APPSECRET,
    # 종목 정보 자동 동기화 여부. 기본값은 True입니다.
    market_auto_sync=False,
)

# PyKis 사용 전 1회 이상 sync_all을 호출하여 종목 정보를 불러옵니다.
kis.market.sync_all()

# SK하이닉스 종목을 조회합니다.
stock = kis.market.stock('000660')
# 종목에 대한 정적인 정보를 가져올 수 있습니다.
print(stock.mksc_shrn_iscd, stock.hts_kor_isnm)
```
또한 종목 정보는 [Tutorial#3-시장-조회](https://github.com/Soju06/python-kis/wiki/Tutorial#3-%EC%8B%9C%EC%9E%A5-%EC%A1%B0%ED%9A%8C)의 튜토리얼 처럼 활용할 수 있습니다.

[Tutorial#4-종목-상세](https://github.com/Soju06/python-kis/wiki/Tutorial#4-%EC%A2%85%EB%AA%A9-%EC%83%81%EC%84%B8)에서 종목 Scope를 가져와 활용하시는 것을 추천드립니다.
```py
# SK하이닉스 종목 스코프를 가져옵니다.
stock = kis.stock('000660')

# 현재가를 조회합니다.
price = stock.price()

print(stock.code, stock.name)
print(f'전일대비율: {price.prdy_ctrt:.2f}%')
print(f'현재가: {price.stck_prpr:,}원')
print(f'최저가: {price.stck_lwpr:,}원')
print(f'최고가: {price.stck_hgpr:,}원')
print(f'전일대비: {price.prdy_vrss:,}원')
print(f'전일대비거래량비율: {price.prdy_vrss_vol_rate:.2f}%')
print(f'거래대금: {price.acml_tr_pbmn:,}원')
```

**Comment by jhyunetp** [comment]
좋은 답변 감사드립니다. 혹시 아래와 같은 오류가 리눅스에서 지속적으로 발생하여 제거를 고려하는 중인데 그 원인을 알고 계십니까?
리눅스에선 혹시 해당 기능을 끄고 진행해야 하는걸까요?
질문의 Thread를 나누어야 한다면 나누겠습니다. 감사합니다.

``[2023-07-17 14:08:57 +0900] [795] [EROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1934, in _exec_single_context
    self.dialect.do_executemany(
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 918, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: kospi.mksc_shrn_iscd

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/sts/sts/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/ubuntu/sts/sts_app/apps.py", line 10, in ready
    from .schedule_job import main
  File "/home/ubuntu/sts/sts_app/schedule_job.py", line 32, in <module>
    master_kis = PyKis(appkey=APPKEY,appsecret=APPSECRET,virtual_account=IS_VIRTUAL,)
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/pykis/kis.py", line 67, in __init__
    self.init()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/pykis/kis.py", line 81, in init
    self.market._init()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/pykis/market/client.py", line 71, in _init
    self._sync_all(comp=False, verbose=False)
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/pykis/market/client.py", line 107, in _sync_all
    self[code].sync()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/pykis/market/base.py", line 113, in sync
    self._sync()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/pykis/market/base.py", line 119, in _sync
    self._update(data.decode(self.encoding))
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/pykis/market/base.py", line 136, in _update
    sess.commit()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1920, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1236, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1211, in _prepare_impl
    self.session.flush()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
    with util.safe_reraise():
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1043, in _emit_insert_statements
    result = connection.execute(
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1934, in _exec_single_context
    self.dialect.do_executemany(
  File "/home/ubuntu/sts/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 918, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: kospi.mksc_shrn_iscd
[SQL: INSERT INTO kospi (mksc_shrn_iscd, stnd_iscd, hts_kor_isnm, scrt_grp_cls_code, avls_scal_cls_code, bstp_larg_div_code, bstp_medm_div_code, bstp_smal_div_code, mnin_cls_code_yn, low_current_yn, sprn_strr_nmix_issu_yn, kospi200_apnt_cls_code, kospi100_issu_yn, kospi50_issu_yn, krx_issu_yn, etp_prod_cls_code, elw_pblc_yn, krx100_issu_yn, krx_car_yn, krx_smcn_yn, krx_bio_yn, krx_bank_yn, etpr_undt_objt_co_yn, krx_enrg_chms_yn, krx_stel_yn, short_over_cls_code, krx_medi_cmnc_yn, krx_cnst_yn, krx_scrt_yn, krx_ship_yn, krx_insu_yn, krx_trnp_yn, sri_nmix_yn, stck_sdpr, frml_mrkt_deal_qty_unit, ovtm_mrkt_deal_qty_unit, trht_yn, sltr_yn, mang_issu_yn, mrkt_alrm_cls_code, mrkt_alrm_risk_adnt_yn, insn_pbnt_yn, byps_lstn_yn, flng_cls_code, fcam_mod_cls_code, icic_cls_code, marg_rate, crdt_able, crdt_days, prdy_vol, stck_fcam, stck_lstn_date, lstn_stcn, cpfn, stac_month, po_prc, prst_cls_code, ssts_hot_yn, stange_runup_yn, krx300_issu_yn, kospi_issu_yn, sale_account, bsop_prfi, op_prfi, thtr_ntin, roe, base_date, prdy_avls_scal, grp_code, co_crdt_limt_over_yn, secu_lend_able_yn, stln_able_yn) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [('F70101B95', 'KR570101B954', '밀라노부동산', 'BC', '', '0000', '0000', '0000', 0, 0, None, '0', 0, 0, 0, '', 0, 0, None, None, None, None, 0, None, None, '0', None, None, None, None, None, None, None, 600, 1, 0, 0, 0, 0, '00', 0, 0, 0, '00', '00', '00', 100, 0, 90, 0, 1000, '2019-05-21', 53532, 53532869000, None, None, '0', None, 0, 0, 0, 0, 0, 0, 0, 0.0, None, 321, '', 0, 0, 0), ('F70101B96', 'KR570101B962', '벨기에코어오피스2호', 'BC', '', '0000', '0000', '0000', 0, 0, None, '0', 0, 0, 0, '', 0, 0, None, None, None, None, 0, None, None, '0', None, None, None, None, None, None, None, 618, 1, 0, 0, 0, 0, '00', 0, 0, 0, '00', '00', '00', 100, 0, 90, 0, 1000, '2019-09-11', 90948, 90948788000, None, None, '0', None, 0, 0, 0, 0, 0, 0, 0, 0.0, None, 562, '', 0, 0, 0), ('F70101B99', 'KR570101B996', '한국투자도쿄한조몬오피스', 'BC', '', '0000', '0000', '0000', 0, 0, None, '0', 0, 0, 0, '', 0, 0, None, None, None, None, 0, None, None, '0', None, None, None, None, None, None, None, 900, 1, 0, 0, 0, 0, '00', 0, 0, 0, '00', '00', '00', 100, 0, 90, 0, 1000, '2019-09-02', 61469, 61469664000, None, None, '0', None, 0, 0, 0, 0, 0, 0, 0, 0.0, None, 553, '', 0, 0, 0), ('F70101B9A', 'KR570101B9A2', '한국투자뉴욕오피스1호', 'BC', '', '0000', '0000', '0000', 0, 0, None, '0', 0, 0, 0, '', 0, 0, None, None, None, None, 0, None, None, '0', None, None, None, None, None, None, None, 780, 1, 0, 0, 0, 0, '00', 0, 0, 0, '00', '00', '00', 100, 0, 90, 0, 1000, '2020-01-21', 126300, 126300000000, None, None, '0', None, 0, 0, 0, 0, 0, 0, 0, 0.0, None, 985, '', 0, 0, 0), ('F70101BA2', 'KR570101BA26', '한투소재부품장비A', 'BC', '', '0000', '0000', '0000', 0, 0, None, '0', 0, 0, 0, '', 0, 0, None, None, None, None, 0, None, None, '0', None, None, None, None, None, None, None, 1030, 1, 0, 0, 0, 0, '00', 0, 0, 0, '00', '00', '00', 100, 0, 90, 0, 1000, '2020-04-27', 22440, 22440318000, None, None, '0', None, 0, 0, 0, 0, 0, 0, 0, 0.0, None, 231, '', 0, 0, 0), ('F70101BA7', 'KR570101BA75', '한국투자도쿄기오이쵸오피스[파생형]', 'BC', '', '0000', '0000', '0000', 0, 0, None, '0', 0, 0, 0, '', 0, 0, None, None, None, None, 0, None, None, '0', None, None, None, None, None, None, None, 1035, 1, 0, 1, 0, 0, '00', 0, 0, 0, '00', '00', '00', 100, 0, 90, 0, 1000, '2020-10-28', 42265, 42265148000, None, None, '0', None, 0, 0, 0, 0, 0, 0, 0, 0.0, None, 437, '', 0, 0, 0), ('F70101BB1', 'KR570101BB17', '한국투자서울오피스', 'BC', '', '0000', '0000', '0000', 0, 0, None, '0', 0, 0, 0, '', 0, 0, None, None, None, None, 0, None, None, '0', None, None, None, None, None, None, None, 1000, 1, 0, 0, 0, 0, '00', 0, 0, 0, '00', '00', '00', 100, 0, 90, 0, 1000, '2021-03-17', 54764, 54764919000, None, None, '0', None, 0, 0, 0, 0, 0, 0, 0, 0.0, None, 547, '', 0, 0, 0), ('F70102B96', 'KR570102B960', '룩셈부르크코어오피스(파생형)(A)', 'BC', '', '0000', '0000', '0000', 0, 0, None, '0', 0, 0, 0, '', 0, 0, None, None, None, None, 0, None, None, '0', None, None, None, None, None, None, None, 1005, 1, 0, 0, 0, 0, '00', 0, 0, 0, '00', '00', '00', 100, 0, 90, 0, 1000, '2019-09-20', 81072, 81072205000, None, None, '0', None, 0, 0, 0, 0, 0, 0, 0, 0.0, None, 814, '', 0, 0, 0)  ... displaying 10 of 2176 total bound parameter sets ...  ('Q760005', 'KRG760000056', '키움 INDXX 미국테크탑10 ETN', 'EN', '', '0000', '0000', '0000', 0, 0, None, '0', 0, 0, 0, '3', 0, 0, None, None, None, None, 0, None, None, '0', None, None, None, None, None, None, None, 14800, 1, 1, 0, 0, 0, '00', 0, 0, 0, '00', '00', '00', 50, 0, 90, 31, 0, '2022-12-22', 10000, 0, None, None, '0', None, 0, 0, 0, 0, 0, 0, 0, 0.0, None, 1480, '', 0, 0, 0), ('900140', 'KYG5307W1015', '엘브이엠씨홀딩스', 'FS', '', '0000', '0000', '0000', 0, 0, 0, '0', 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '0', 0, 0, 0, 0, 0, 0, 0, 2595, 1, 1, 0, 0, 0, '00', 0, 0, 0, '00', '00', '00', 100, 0, 90, 1655385, 0, '2010-11-30', 171588, 42897103, 12, None, '0', None, 0, 0, 0, 821, 67, -75, -73, -7.26, '2023-03-31', 4452, '', 0, 0, 0)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)``

**Comment by Soju06** [comment]
리눅스 환경에서 테스트 해보았지만 일반적인 환경에서는 문제가 발견되지 않았습니다.
traceback을 보아 gunicorn을 사용하여 multiple worker를 사용하는 것 같은데, 이 때문에 발생한 문제라고 추측합니다.
현재 market db는 sqlite로 `path.join(tempfile.gettempdir(), f".pykis-cache_market.{MARKET_VERSION}.db")` 경로에 임시 저장합니다.
하지만 python-kis는 PyKis 자체를 다중으로 생성했을 때를 고려하지 않았기에 PyKis 객체를 한 개만 생성하고 이를 공유하여 사용하는 방식으로 작성해야 할 것 같습니다.
이는 추측이며 정확하지 않을 수 있습니다.
혹시 재현이 가능한 코드를 제공해 주실 수 있으신가요?

**Comment by jhyunetp** [comment]
@Soju06 님 감사합니다. 확인해본 결과 multiple worker를 사용했기 때문에 발생했던 문제였습니다.
말씀해주신대로 하나의 객체를 생성하고 그것을 여러 workers에서 공유하는 방식으로 변경한 결과 동일한 문제가 발생하지 않았습니다.
인프라에 대한 부족한 경험으로 파악이 늦어졌는데 질문을 드려 시간을 뺏어 죄송합니다.
